portainer/k8s

charts/portainer/Chart.yaml
charts/portainer/README.md
charts/portainer/templates/service.yaml
charts/portainer/values.yaml

Add service annotations field to Helm Chart

---

deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml

Fix use of deprecated ClusterRoleBinding API

---

.ci/scripts/generate-portainer-manifests-from-chart.sh
charts/portainer/Chart.yaml
charts/portainer/templates/service.yaml
deploy/manifests/portainer/portainer.yaml

Unable to use Edge agent with Portainer exposed over node port

---

.ci/scripts/generate-portainer-manifests-from-chart.sh
README.md
charts/portainer/Chart.yaml
charts/portainer/templates/deployment.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/README.md
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/ee/portainer-edge-agent-setup.sh
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml

Support Portainer EE deployment

---

charts/portainer/Chart.yaml

Release non-pre version of Chart 1.0.6

Release non-pre version of Chart 1.0.6

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Fixes #37
Signed-off-by: David Young <davidy@funkypenguin.co.nz>

Bump chart appversion to 2.0.1

---

.github/workflows/on-push-lint-charts.yml
.github/workflows/on-push-master-publish-chart.yml

Signed-off-by: David Young <davidy@funkypenguin.co.nz>

Improve CI testing

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml

Fixes #44
Signed-off-by: David Young <davidy@funkypenguin.co.nz>

Update appVersion to ce-latest-ee-2.0.0, add storageClass to values.yaml

---

.ci/scripts/generate-portainer-manifests-from-chart.sh
README.md
charts/portainer/Chart.yaml
charts/portainer/templates/namespace.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Fixes #49
Signed-off-by: David Young <davidy@funkypenguin.co.nz>

Include namespace in manifests

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-ee20-windows.yml
deploy/manifests/agent/ee/agent-stack-ee20.yml
deploy/manifests/agent/ee/agent-stack-ee24-windows.yml
deploy/manifests/agent/ee/agent-stack-ee24.yml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-ee20-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-ee20-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-ee20-k8s-nodeport.yaml
deploy/manifests/agent/ee/portainer-agent-ee24-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-ee24-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-ee24-k8s-nodeport.yaml
deploy/manifests/agent/ee/portainer-ee20-edge-agent-setup.sh
deploy/manifests/agent/ee/portainer-ee24-edge-agent-setup.sh
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

* update ee version to 2.4.0
* use file versioning for ee agent
* update ee agent version to 2.4.0

Update ee version to 2.4.0

---

deploy/manifests/agent/ee/portainer-agent-ee24-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-ee24-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-ee24-k8s-nodeport.yaml
deploy/manifests/agent/ee/portainer-ee24-edge-agent-setup.sh

Add ee agent 2.4 files

---

deploy/manifests/agent/ee/portainer-agent-ee210-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-ee210-edge-agent-setup.sh
deploy/manifests/agent/portainer-ce29-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-ce29-edge-agent-setup.sh

[EE-332]
[EE-332]: https://portainer.atlassian.net/browse/EE-332

feat(agent): support insecure poll flag

---

.github/workflows/on-push-lint-charts.yml
charts/portainer/Chart.yaml
charts/portainer/templates/NOTES.txt
charts/portainer/templates/deployment.yaml
charts/portainer/templates/service.yaml
charts/portainer/values.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

First cut at changes required for SSL support

Update chart to support BYO SSL certificates

---

charts/portainer/Chart.yaml
charts/portainer/templates/NOTES.txt
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Fix for helper text pointing to wrong port when tls.force is enabled for nodeport

2.13.1 Update

---

charts/portainer/Chart.yaml
charts/portainer/templates/NOTES.txt
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Fix notes for loadbalancer url 
update chart for 2.15 release

release 2.15

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Test and merge only after 2.17 release image is created.

update and bump for 2.17

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Update version to 2.17.1

---

charts/portainer/Chart.yaml
charts/portainer/templates/deployment.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

The update includes increasing the timeout for readiness and liveness:
```sh
failureThreshold: 3
initialDelaySeconds: 45
```

feat(helm): update to `2.18.2`

---

charts/portainer/Chart.yaml
charts/portainer/templates/deployment.yaml
charts/portainer/values.yaml

add periodSeconds:30 to liveness and readiness probes  to stop pod from restarting before its ready.

add periodSeconds:30 to liveness and readiness probes 

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Version bump for 2.19.5

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Update for 2.21.1

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Update Helm chart for 2.21.3

---

charts/portainer/Chart.yaml
charts/portainer/templates/deployment.yaml
charts/portainer/values.yaml

Add option to set tolerations 

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Changed image tags and bumped chart version

release 2.27.0

---

charts/portainer/Chart.yaml
charts/portainer/values.yaml
deploy/manifests/agent/ee/agent-stack-windows.yml
deploy/manifests/agent/ee/agent-stack.yml
deploy/manifests/agent/ee/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml
deploy/manifests/agent/portainer-agent-edge-k8s.yaml
deploy/manifests/agent/portainer-agent-k8s-lb.yaml
deploy/manifests/agent/portainer-agent-k8s-nodeport.yaml
deploy/manifests/portainer/portainer-ee.yaml
deploy/manifests/portainer/portainer-lb-ee.yaml
deploy/manifests/portainer/portainer-lb.yaml
deploy/manifests/portainer/portainer.yaml

Updated files for 2.33.0 and chart version to match

Release 2.33.0
